### ISSUE TITLE
vcoco version

### ISSUE THREAD

**Issue by SISTMrL** [yoyomimi/AS-Net#13]
hello, could you please release the vcoco version code, thanks!

**Comment by yoyomimi** [comment]
The vcoco annotations we used can be downloaded from here: [vcoco annotations, best checkpoint and results](https://drive.google.com/drive/folders/1deDU5NyZ6m5ODNalzLch7nvcmYwPVxia?usp=sharing).
The annotation format and object categories are the same as HICO-DET, you can change the action related category related setting in the hico.yaml and train on v-coco. The evaluation process can be referred to [v-coco](https://github.com/s-gupta/v-coco).

**Comment by imkzh** [comment]
@yoyomimi I downloaded the `all_vcoco_test_result.pkl` but failed to run evaluation code from `s-gupta/v-coco` with it.

```
>>> from vsrl_eval import VCOCOeval
>>> v = VCOCOeval("data/vcoco/vcoco_val.json", "data/instances_vcoco_all_2014.json", "data/splits/vcoco_val.ids")
>>> v._do_eval('/home/user/Desktop/all_vcoco_test_result.pkl', ovr_thresh=0.5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/storage1/datasets/vcoco/v-coco/vsrl_eval.py", line 193, in _do_eval
    self._do_role_eval(vcocodb, detections_file, ovr_thresh=ovr_thresh, eval_type='scenario_1')
  File "/media/storage1/datasets/vcoco/v-coco/vsrl_eval.py", line 316, in _do_role_eval
    assert(np.amax(rec) <= 1)
  File "<__array_function__ internals>", line 5, in amax
  File "/usr/local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2705, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/usr/local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

Any hint on this?
